In [1]:
import numpy as np

In [2]:
#step 1: collect data

X=np.array([

    [2,3,4],

    [3,5,6],

    [5,8,9],

    [6,9,11],

    [7,10,13]

])

In [3]:
#step 2: compute mean value for each column

mean_X=np.mean(X,axis=0)

print(mean_X)

[4.6 7.  8.6]


In [4]:
#step 3: center the data

X_centered=X - mean_X

print(X_centered)

[[-2.6 -4.  -4.6]
 [-1.6 -2.  -2.6]
 [ 0.4  1.   0.4]
 [ 1.4  2.   2.4]
 [ 2.4  3.   4.4]]


In [5]:
#step 4: compute the covariance matrix

cov_matrix = np.cov(X_centered,rowvar=False)

print(cov_matrix)

[[ 4.3   6.    7.55]
 [ 6.    8.5  10.5 ]
 [ 7.55 10.5  13.3 ]]


In [6]:
#step 5: compute eighenvalues and eigenvector

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print(eigenvalues)

print(eigenvectors)

[2.59637803e+01 5.52557327e-03 1.30694106e-01]
[[ 0.4066816   0.90812885  0.09955937]
 [ 0.56930735 -0.16669075 -0.80504865]
 [ 0.71449228 -0.38407836  0.58479449]]


In [7]:
# Step 6: Select Principal Components (Sorting by largest eigenvalues)

sorted_indices = np.argsort(eigenvalues)[::-1]

eigenvalues = eigenvalues[sorted_indices]

eigenvectors = eigenvectors[:, sorted_indices]

In [8]:
# Step 7: Transform the Data

# 3 to 1 (Project onto first principal component)

X_transformed_1 = X_centered @ eigenvectors[:, 0]

In [9]:
# 3 to 2 (Project onto first two principal components)

X_transformed_2 = X_centered @ eigenvectors[:, :2]

# Output results

print("Transformed Data (3 to 1):")

print(X_transformed_1)

print("\nTransformed Data (3 to 2):")

print(X_transformed_2)

Transformed Data (3 to 1):
[-6.62126605 -3.64698519  1.0177769   3.42275041  5.82772392]

Transformed Data (3 to 2):
[[-6.62126605  0.27128556]
 [-3.64698519 -0.06966338]
 [ 1.0177769  -0.5313071 ]
 [ 3.42275041 -0.0672074 ]
 [ 5.82772392  0.39689231]]
